In [1]:
import numpy as np

In [6]:
a = np.array([[1,2,3,],[3,4,5]],dtype='int32')
a

array([[1, 2, 3],
       [3, 4, 5]], dtype=int32)

In [3]:
a.ndim

2

In [4]:
a.shape

(2, 3)

In [7]:
a.dtype

dtype('int32')

In [9]:
a.itemsize
a.nbytes
#size deta hai

24

In [16]:
zero=np.zeros((2,3))
zero
zero=np.ones((2,3))
zero

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
random=np.full((3,5),99)
random

array([[99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99]])